config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  root "static_pages#landing_page"
  resources :articles do
    resources :comments
  end
  resources :user do
  end

  get "/welcome", as: "landing_page", to: "static_pages#landing_page"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article
  belongs_to :user

  def set_commenter
    update(commenter: user.username)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
        articles_path
      end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  def index
    @IsATrap = false
    @articles = Article.all
  end
  def show
    @Article = Article.find(params[:id])
    @Article.increment!(:views)
    @comments = @Article.comments.includes(:user)
  end
  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article 
    
    else
      render :new
    end
  end
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
    def create
        @Article = Article.find(params[:article_id])
        @comment = current_user.comments.create(comment_params)
        redirect_to article_path(@Article)
    end
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end 

  private
    def comment_params
      params.require(:comment).permit(:article_id, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    layout "landing"
    def landing_page
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def index
    end

    def show
        @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article, class:"card w-50 p-3 m-3 shadow" do |form| %>
  <div class="form-group">
    <%= form.label :title, class:"form-label" %><br>
    <%= form.text_field :title, class:"form-control" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :body, class:"form-label" %><br>
    <%= form.text_area :body, class:"form-control" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "send", class:"btn btn-primary" %>
  </div>


<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="container my-4">
  <div class="d-flex justify-content-between mx-3">
    <div class="align-items-start">
      <h1 class="text text-success text-center">Recent Posts</h1>
    </div>
    <div class="align-items-end">
      <%= link_to "New Article", new_article_path, class:"btn btn-primary m-2" %>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-2 g-0">
    <% @articles.each do |article| %>
      <div class="card">
        <div class="card-header">
          <h5 class="card-title"><%= article.title %></h5>
        </div>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">Descripcion:</h6>
          <p class="card-text"><%= article.body %></p>
          <%= link_to "see more", article_path(article), class: "card-link" %>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
    <% end %>
  </div>
</div>
  

app/views/articles/new.html.erb
<h1 class="text text-success text-center">New Article</h1>

<%= render "form", article: @article %>
<%= link_to "back", articles_path, class:"m-3" %>

app/views/articles/show.html.erb
<h1 class="text text-success text-center"><%= @Article.title%></h1>
<h2 class="text text-center"><%= @Article.body%></h2>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid d-flex justify-content-center">
    <div class="row d-flex ">
      <ul class="nav navbar-nav"> 
        <li class="nav-item mx-5"><p class="badge bg-warning text-dark"><%= "Views: #{@Article.views}"%></p>
        <li class="nav-item mx-5"><%= link_to "Edit", edit_article_path(@Article), class:"btn btn-success" %></li>
        <li class="nav-item mx-5"><%= link_to "Destroy", article_path(@Article),
                        method: :delete,
                        data: { confirm: "Are you sure?" }, class:"btn btn-danger" %></li>
        <li class="nav-item mx-5"><%= link_to "back", articles_path, class:"btn btn-info" %></li>
      </ul>
    </div>
  </div>
</nav>


<h3 class="m-2">Comments</h3>
<% @comments.each do |comment| %>
  <p>Created by: <%= comment.user.username%></p>
  <p>Body: <%= comment.body%></p>
<% end %>

<h4>Add a comment:</h4>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div class="card">
  <div class="">
    <p class="mb-0">
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
  </div>
  <div class="">
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
    <div >
      <%= image_tag ("doge.jpg"), class:"img-thumbnail responsive-doge-img"%> 
    </div>
  </div>
</div>

<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" }, class:"btn btn-danger my-2 mx-1" %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @Article, @Article.comments.build ], class:"card w-50 p-3 m-3 shadow" do |form| %>
  <%= form.hidden_field :article_id, value: @Article.id %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control" %>
  </p>
  <p>
    <%= form.submit "Create", class:"btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="bg-light d-flex flex-column min-vh-100">
  
    <header class="p-3 bg-dark text-white">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use href="ruby.svg"></use></svg>
            </a>
        
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a class="nav-link px-2 text-success">Tutorial de Rails</a></li>
              <li><a class="nav-link px-2 text-white">better than reddit, ik</a></li>
              <%# <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
              <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
              <li><a href="#" class="nav-link px-2 text-white">About</a></li> %>
              <%= button_to "logout", destroy_user_session_path, method: :delete  %>
            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input type="search" class="form-control form-control-dark" placeholder="Search...">
            </form>
            
              <%= link_to "View Profile", user_path(current_user), class:"btn btn-outline-light" %>
                        <%# <div class="text-end">
              <button type="button" class="btn btn-outline-light me-2">Login</button>
              <button type="button" class="btn btn-warning">Sign-up</button>
            </div> #%>
          </div>
        </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
            
    <%= yield %>
    
    <footer class="footer mt-auto py-3 bg-dark ">
      <div class="container">
        <h6 class="text-muted text-center">Tutorial de Rails</h6>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="text-center text-white bg-dark">
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
            
    <%= yield %>

  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex h-100 text-center text-white bg-dark">
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
            
    <%= yield %>

  </body>
</html>

app/views/static_pages/landing_page.html.erb
<div class="container d-flex w-100 h-100 p-3 m-5 flex-column">
    <div class="px-3 row align-items-center">
        <h1 class="mb-3">Welcome</h1>
        <p class="lead mb-5">To the best page in humanity's existence.</p>
        <ul class="nav justify-content-center">
            <li><%= link_to 'Log In', new_user_session_path, class: 'btn btn-outline-light m-3 fw-bold' %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-light m-3 fw-bold' %></li>
        </ul>
    </div>
</div>

app/views/user/index.html.erb
<h1>Index</h1>

app/views/user/show.html.erb
<h1>Perfil</h1>
<% if @user.avatar.attached? %>
    
<% end %>
<image src="<%=(url_for(@user.avatar))%>", class="w-25 h-25">
<h1><%= @user.username %></h1>
<h1><%= @user.email %></h1>